title: HEALTH CHECK LOAD BALANCER
description: >-
  Configuration health checks allow a load balancer to stop sending traffic to a
  node that is not responding if a pre configured check fails on that node. If
  the appliance is offline due to maintenance or unexpected failure.
template:
  repo: health-check-load-balancer-template
  name: health-check-load-balancer
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
